# Generated by Django 5.0.6 on 2025-01-15 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_eventparticipant_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(unique=True, verbose_name='Дата и время')),
                ('total_seats', models.PositiveIntegerField(default=0, verbose_name='Всего мест')),
            ],
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.eventsession', verbose_name='Сеанс мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.event'),
        ),
        migrations.AddField(
            model_name='eventsession',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_sessions', to='main.session', verbose_name='Сессия'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsession',
            unique_together={('event', 'session')},
        ),
        migrations.RemoveField(
            model_name='eventsession',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='eventsession',
            name='total_seats',
        ),
    ]
